### ISSUE TITLE
Generate vocabularies indexing resources in RDF

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-backend#17]
## I expect

- a RDF resource according to the NDC AP profile to be generated https://github.com/italia/daf-ontologie-vocabolari-controllati/pull/121/files
- the resource to be added to the model when stored

**Comment by ronytw** [comment]
This has been implemented. See https://virtuoso-dev-external-service-ndc-dev.apps.cloudpub.testedev.istat.it/sparql?default-graph-uri=&query=select+distinct+%3Fprop+%3Fvalue+where+%7B+%3Chttps%3A%2F%2Fw3id.org%2Fitalia%2Fdata%2Fdata-service%2FISTAT-parental-relationship-types%3E+%3Fprop+%3Fvalue%7D&format=text%2Fhtml
for an example.

We can probably close this?
