### ISSUE TITLE
Consistent "offset" and "totalCount" datatypes

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-backend#24]
## I expect

- `offset` and `totalCount` datatype should match

## Instead

- offset is int32
- totalCount is int64
- we don't expect to have vocabularies with more than 1G entries.

## Possibili soluzioni
Always int32

## Contesto

see OAS3 spec

**Comment by ash1425** [comment]
Yes, this seems like the oversight. Changing them.

**Comment by ash1425** [comment]
fixed in https://github.com/teamdigitale/dati-semantic-backend/pull/26.
