### ISSUE TITLE
[BE] Support `assets/` paths

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-backend#37]
## I expect

To harvest first following paths:

`assets/{ontologies,vocabularies,schemas}`

## Instead

It only procesesses ontopia-like paths `Ontologie,VocabolariControllati`

## Possibili soluzioni

Extend the static class to support both, considering that Ontopia-like paths are a legacy.

A configuration parameter has been considered and excluded.

**Comment by Clou-dia** [comment]
Hi, how can we test it? @gnespolino

**Comment by Clou-dia** [comment]
from dev or test I cannot see inail assets, I can only see the changes in the PR.

**Comment by gnespolino** [comment]
> from dev or test I cannot see inail assets, I can only see the changes in the PR. What do you mean by "We also added Inail to the repo lists"? You changed the possible folder organization and name

we added support for asset/** folder, leaving the legacy folder name support.
So yes, Inail repo should be harvested now, but you probably we need to wait the harvester to run.

**Comment by gnespolino** [comment]
> from dev or test I cannot see inail assets, I can only see the changes in the PR. What do you mean by "We also added Inail to the repo lists"? You changed the possible folder organization and name

I just triggered an harvesting manually both on dev and test, result should be visible in a couple of minutes.

**Comment by gnespolino** [comment]
> can you confirm this are the url: https://ndc-test.apps.cloudpub.testedev.istat.it/ https://ndc-dev.apps.cloudpub.testedev.istat.it/
> 
> Still didn't see anything from inail, so far.

Good morning @Clou-dia, let me finish some work on it (there was a naming error in the vocabularies folder). I'll ping you when it's ready.

**Comment by Clou-dia** [comment]
https://github.com/teamdigitale/dati-semantic-backend/pull/78

**Comment by Clou-dia** [comment]
@gnespolino è risolto?

**Comment by gnespolino** [comment]
> @gnespolino è risolto?

yes, legacy paths are still supported as well.
New supported paths are [here](https://github.com/teamdigitale/dati-semantic-backend/blob/f9d6d35caa704f7b2e032cb8940a31d215f654c6/src/main/java/it/gov/innovazione/ndc/harvester/SemanticAssetType.java#L8-L18)

**Comment by Clou-dia** [comment]
Verified, thanks
