### ISSUE TITLE
[BE] Grouping ontologies in the same folder

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-backend#41]
## I expect

- grouping ontologies that change together in the same folders
- I don't want to use intermediate folders to achieve this behavior

```
ontologies/
  OntoGroup1:
      latest/
         onto1.ttl
         onto2.ttl
      0.9/
         onto1.ttl
         onto2.ttl
  OntoGroup2
      latest/
         onto3.ttl
         onto4.ttl
```

## Comportamento attuale

This is currently achieved with a completely different layout wrt the default one.

```
ontologies/
      latest/
          Onto1: 
              onto1.ttl
          Onto2:         
              onto2.ttl
      0.9/
         Onto3:
               onto3.ttl
```

**Comment by giorgialodi** [comment]
@Clou-dia non mi è chiaro questo issue perché il comportamento attuale non è quello di OntoPiA e di altri repository che abbiamo visto. Non so nemmeno se gli URI funzionano con queste cose. Un folder per una ontologia e basta.

**Comment by giorgialodi** [comment]
@Clou-dia I suggest closing it if it is not clarified further.

**Comment by ioggstream** [comment]
@giorgialodi ok. Attualmente l'harvester implementa un complesso meccanismo di alberatura che va rimosso.
