### ISSUE TITLE
[BE] Semantic assets updated in github but not in schema

### ISSUE THREAD

**Issue by giorgialodi** [teamdigitale/dati-semantic-backend#63]
## Comportamento atteso
I expect that changes in the semantic assets are clearly showed in schema (e.g., change in last modification date)

## Comportamento attuale
We have recently revised a controlled vocabulary on sex, but the fact that the vocabulary has been modified is not shown in schema. 
<img width="1061" alt="Screenshot 2023-03-17 at 08 52 00" src="https://user-images.githubusercontent.com/24624577/225844984-80377388-8169-49d8-a9ea-a78bea60cea1.png">
The source code of the vocabulary indicates that the last modification date is 15/03/2023 but in the catalog is still set to 2018. 
Also, if I navigate the vocabulary with LodView using vocabulary's URI, this does not seem up-to-date according to the source code in the related github repository.

## Possibili soluzioni
Is that possible that the issue is in the mechanism of deleting the content of the SPARQL endpoint in order to recreate it with the new assets taken from the Github repository?

**Comment by gnespolino** [comment]
@Clou-dia might be usefull if you or someone else could test whether these issues are still valid, since some of them might have been fixed in previous releases.

**Comment by giorgialodi** [comment]
@gnespolino I close the issue because it seems now working
