### ISSUE TITLE
[BE] API in Vocabolari controllati: 404 error on API service-input-output

### ISSUE THREAD

**Issue by lorello** [teamdigitale/dati-semantic-backend#65]
## Comportamento atteso

l'utilizzo del path `/vocabularies/{agency_id}/{key_concept}` dovrebbe restituire il vocabolario

l'utilizzo del path `/vocabularies/{agency_id}/{key_concept}/{id}` dovrebbe restituire una specifica voce del vocabolario

## Comportamento attuale

in ambedue i casi usando `agency_id=agid` e `key_concept=service-input-output` ottengo HTTP response status codes 404 con messaggio

URL chiamata: `https://www.schema.gov.it/api/vocabularies/agid/service-input-output`

Risposta:
```
{
    "status": 404,
    "timestamp": "2023-04-17T17:30:17.599486",
    "title": "Unable to find vocabulary data for : agid.service-input-output",
    "type": "https://www.schema.gov.it/tech/errors/VocabularyDataNotFoundException"
}
```

**Comment by Clou-dia** [comment]
same as https://github.com/teamdigitale/dati-semantic-backend/issues/61

**Comment by gnespolino** [comment]
seems to work:

https://schema.gov.it/api/vocabularies/agid/service-input-output?limit=10&offset=0

@CreaIstat can be closed.

**Comment by Clou-dia** [comment]
before closing issue we need to test

**Comment by gnespolino** [comment]
> before closing issue we need to test

Some issues are quite old, please if someone could actually test them and leave open only the ones still reproducible, it would really help.

**Comment by Clou-dia** [comment]
Closing this to open a new thread for resolution
