### ISSUE TITLE
Aggiornamenti fatti su repo ontologie di github italia non si riflettono in schema

### ISSUE THREAD

**Issue by giorgialodi** [teamdigitale/dati-semantic-backend#81]
## Comportamento atteso
Mi aspetto che i cambiamenti apportati al repo github italia OntoPiA si riflettano in schema ogni volta che l'harvester viene messo in funzione alle 22

## Comportamento attuale
La scorsa settimana è stata apportata una modifica al vocabolario controllato dei comuni ma questa modifica non è ancora stata acquisita da schema. Se navigo il vocabolario vedo ancora il bug, sebbene sia stato corretto https://github.com/italia/daf-ontologie-vocabolari-controllati/commit/b2f9729507bace5e0f7b72fe959bab0e9cf3c26d

## Possibili soluzioni
Siete sicuri di utilizzare il repo di github italia e non magari la copia su github ISTAT? 

/cc @gnespolino @Clou-dia

**Comment by gnespolino** [comment]
Ciao @giorgialodi , non so se in via precauzionale, dati i problemi che si erano riscontrati su Virtuoso DEV/TEST, al momento la schedulazione dell'harvester sia o meno attiva.
Indago e vi aggiorno.

**Comment by giorgialodi** [comment]
Ciao @gnespolino  grazie per il riscontro e per il check. È importante e urgente far sì che schema in produzione recepisca quel fix che è stato fatto.
